ARMmbed/sd-driver

features/filesystem/sd/SDBlockDevice.cpp
features/filesystem/sd/SDBlockDevice.h

This is needed to compile with the release of mbed OS. Otherwise constraint is not matched on the member function.
cc @simonqhughes, @c1728p9

Fix const attribute mismatch on size function

---

README.md
config/mbed_lib.json
features/TESTS/examples/example1/example1.cpp
features/TESTS/filesystem/basic/basic.cpp
features/TESTS/filesystem/fopen/fopen.cpp

Modify example also similarly to match the PIN definitions. This encapsulates
all the SD-card related stuff to this library. By including this library you
also get the pin definitions on the same go.

Start using mbed_lib.json

---

config/mbed_lib.json

Enable the internal SD-card reader in UBLOX_EVK_ODIN_W2. This will
disable the CI-shield SD-card reader if you have, if you prefer using it
you have to remove this target override section.
Please note that there seem to be some reliability problems with the
internal SD-card slot, in my case the mbed OS CI-shield works better.

Add UBLOX_EVK_ODIN_W2 override for int. SD-card

---

features/filesystem/sd/SDBlockDevice.cpp

Incorrect bits of CSD structure were used to calculate card capacity, corrected that and modified print statements and some comments to share information from specifications

Card capacity calculation corrected to csd [69,48]

---

features/filesystem/sd/SDBlockDevice.cpp
features/filesystem/sd/SDBlockDevice.h

With reference to [PR18](https://github.com/ARMmbed/sd-driver/pull/18): 
Added new frequency function to update the transfer frequency. Max frequency is limited to 25MHZ at present. In future higher frequency with switch to different SDR modes in SD will be supported.

Function to update transfer freq

---

TESTS/filesystem/fopen/fopen.cpp

This updates the tests to check for '.' and '..', otherwise the tests fail when the expected file is not first in the directory iteration.
Note: This is related to https://github.com/ARMmbed/mbed-os/pull/4186, and should not be merged unless https://github.com/ARMmbed/mbed-os/pull/4186 is.
tested locally with K64F, GCC_ARM
cc @simonqhughes

Add checks for '.' and '..' in readdir tests

---

SDBlockDevice.cpp

CMD9 fails for few cards if spi.write is performed during deselect of card.
Card immediately sends start packet token, which goes missing in this dummy write to SPI. Should not clock SPI bus in deselect operation.
Issue #39

CSD Failure

---

TESTS/filesystem/fopen/fopen.cpp

ferror(NULL) is undefined behavior
http://pubs.opengroup.org/onlinepubs/9699919799/functions/ferror.html
cc @marcuschangarm, @deepikabhavnani

Remove test assert on NULL ferror

---

SDBlockDevice.cpp

Using fix from mbed-os core, where few devices were failing with SPI block read, as default data on SPI was sent 0x00. Using API 'set_default_write_value' to set the default tx fill data.
mbed-os dependency: 'set_default_write_value API' change
TODO: 
Merge after OS code is merged and add dependency #error check in code.
@geky @simonqhughes

SPI block read fix

---

SDBlockDevice.cpp

Fix for Issue: Version check will fail for mbed-os master branch.
Checking if version is defined, on master branch no version number is present, so will just issue the warning.

Checking for version, for OS master support

---

SDBlockDevice.cpp

According to the [documentation](http://users.ece.utexas.edu/~valvano/EE345M/SD_Physical_Layer_Spec.pdf) (page 95) you should add one to the value extracted from the CSD to obtain the real erase sector size.

Correct calculation of the erase sector size

---

TESTS/block_device/basic/basic.cpp
config/mbed_lib.json

Adding support for the TARGET_HEXIWEAR SD holder on the base board.  Tested using the cloud client example.

add support for SD card holder on HEXIWEAR base board.

---

config/mbed_lib.json

@MarceloSalazar Add SPI pins setting for support SD card reader/writer over DISCO_L476VG, which is required and tested by using ARMmbed/mbed-cloud-client-example-sources-internal.

Add SD card reader support over DISCO_L476VG platform for running Cloud Client.

---

SDBlockDevice.cpp

Wait for card to be ready is required before sending commands, or performing read/write operations except for CMD12. CMD12 can be sent even if the card is not ready and is used to stop read multiple block operation.

Should not wait for card to be ready when sending stop command

---

.travis.yml

Recently, how pip installs dependencies in travis has changed. Now, installing dependecies with sudo prevents import in user space.
cc @deepikabhavnani

Fix .travis.yml requirements install

---

SDBlockDevice.cpp
SDBlockDevice.h

For better or worse, erase in the block device API is intended for flash erases, which is a low-level operation that must occur before every write and limits the write size of the underlying blocks. This is different than the erase size found in SD cards, which does not limit the write size for blocks.
Following the standard set by ATA and the ioctl function, we are adding a seperate operation for the SD card erase behaviour named trim.
See for more info:
https://en.wikipedia.org/wiki/Trim_(computing)
dependent on https://github.com/ARMmbed/mbed-os/pull/4983
cc @deepikabhavnani

Remove erase in favor of trim

---

README.md

SD driver version is updated to 1.2 to indicate dependency on mbed-os 5.6.1
Relates to PR #57 
@geky

Updated Version and included block device test

---

TESTS/block_device/basic/basic.cpp
TESTS/filesystem/basic/basic.cpp
TESTS/filesystem/fopen/fopen.cpp

FSFAT_SDCARD_INSTALLED  if present in mbed_lib.json which is default, is not accepted by tests.
Allowing FSFAT_SDCARD_INSTALLED define from mbed_lib.json and mbed_app.json files.
Changing erase command to trim in block device test
Issue was seen in https://github.com/ARMmbed/sd-driver/pull/65

FSFAT_SDCARD_INSTALLED - Accepted from mbed_app.json only

---

TESTS/block_device/basic/basic.cpp
config/mbed_lib.json

Thunderboard Sense 2 platfrom from SiLabs needs an external SD card adapter wired into the SPI pins on the expansion headers on the board. This is also part of the Cloud Client porting requirements. This PR adds the SPI pins for this platform.
Tested with Kingston 8GB class 4 card, SD card SPI breakout board & the Cloud Client application on the thunderboard sense 2 platform. Successful connection/registration to Cloud screenshot below:

Adding SPI pins for Thunderboard Sense 2.

---

SDBlockDevice.cpp
SDBlockDevice.h
TESTS/filesystem/fopen/fopen.cpp

Block size and other variables used for device size calculation are set as bd_size_t (64-bit)  instead uint32_t.

Block size as uint32_t gave incorrect device size

---

config/mbed_lib.json

This PR is tested using following environment.
- ARMmbed/mbed-cloud-client-example-internal with esp8266.
- mbed-cloud-sdk-javascript-quickstart

Support SD card driver on DISCO_F429ZI

---

SDBlockDevice.cpp

Version in mbed-os is different if RTOS is not present. Not checking the version number explicitly, but will leave the warning as few API changes were done, and tracking of version is not done for them in mbed-2.
Issue: https://github.com/ARMmbed/sd-driver/issues/76

Incorrect version number was checked for non-rtos config

---

config/mbed_lib.json

I PR to support SD card driver on GR_LYCHEE that is a Renesas new mbed board.
Also I share the SD driver test result of GR_LYCHEE.
[sd-driver-test-result-GR_LYCHEE.txt](https://github.com/ARMmbed/sd-driver/files/1617776/sd-driver-test-result-GR_LYCHEE.txt)

Support SD card driver on GR_LYCHEE

---

config/mbed_lib.json

solve compilation error on Odin MTB target. connect to the relevant pins

Add override MTB Odin target

---

config/mbed_lib.json

It's tested using MCCv 1.3 with Bootloader v3.3.0

Added MCC 1.3 support for NUCLEO_F767ZI

---

SDBlockDevice.cpp
SDBlockDevice.h

This PR fixes the problem of multiple calls to BD init/deinit APIs, by simply adding an init ref count. This is required due to the fact that the mbed-os utility block devices, which may use SD block device as the backing block device, call the underlying init/deinit APIs automatically. 
This PR resolves [#7455](https://github.com/ARMmbed/mbed-os/issues/7455) for the SD block device.

Add init reference count

---

README.md
SDBlockDevice.cpp

Starting mbed-os 5.10 the SD driver has moved into mbed-os.
Therefore this PR is adding a warning in the SD documentation for the incoming depreciation. 
This PR is dependent on PR #7774
https://github.com/ARMmbed/mbed-os/pull/7774

Adding deprecation warning for mbed-os 5.10

---

SDBlockDevice.cpp
SDBlockDevice.h

Adding get_type to SDBlockDevice class after it was added to mbed-os BlockDevice.h class.
This modification is being done although the depreciation of the sd-driver repo because it is affecting the bootloader.

Adding get type method to SDBlockDevice
